---
title: "00_limieza_1"
output: html_document
---

```{r, echo=FALSE, results='hide', include=FALSE, message=FALSE, warning=FALSE}
source("../../utils.R")
source("../../poblacion_geometrias.R")
library(ggthemr)
library(glue)
library(reshape)
library(ggpubr)
library(tidygraph)
library(igraph)
library(ggraph)
library(corrplot)

ggthemr("dust")

### DB conections
con <- pub_connect(s3dir = Sys.getenv("S3_DIR"), schema = Sys.getenv("SCHEMA"))
con1 <- prev_connect()
los_queries <- query_dic()


```



```{r}
library(scales)

quant_labels_pct <- function(variable, no_classes=6){
  quantiles <- quantile(variable, 
                        probs = seq(0, 1, length.out = no_classes + 1),na.rm = TRUE)
  labels <- c()
  for(idx in 1:length(quantiles)){labels <- c(labels, paste0(round(quantiles[idx], 2),"% – ", round(quantiles[idx + 1], 2),'%')) }
  labels <- labels[1:length(labels)-1]
  variable_q <- cut(variable, breaks = quantiles,labels = labels, include.lowest = T)
  return(variable_q)
}

```

# Tabla de programas
```{r}
cves <- c('S072',# prospera
          'S176',# pam 
          'S065',# paja 
          'S071',# pet 
          'S241',# SEVIJE
          'S174',# PEI
          'S052',# LICONSA
          'U009',# COMEDORES
          'U005') %>% # SEGURO POPULAR 
    paste(collapse="', '" )

query <- glue::glue("SELECT cddependencia, cdprograma, nbprograma, cdpadron, 
              count(distinct newid) as beneficiarios_unicos, 
              sum(nuimpmonetario) as monto 
            FROM athena_pub.pub_cleaned_test 
              WHERE anio=2017 AND cdprograma IN ('{cves}') 
              AND try_cast(newid as integer) < 500000000 
              GROUP BY cddependencia, cdprograma,  nbprograma, cdpadron")

c(tabla_programas,los_queries) := load_or_run(con,query,los_queries)
tabla_programas <- tabla_programas %>%
  mutate(monto = if_else(is.na(monto),0,monto),
         porcentaje_de_monto = if_else(!is.na(monto), 
                                       paste0(round((monto*100)/sum(tabla_programas$monto,na.rm = TRUE),digits = 2), " %"),"0 %"),
         porcentaje_de_beneficiarios = if_else(!is.na(beneficiarios_unicos), 
                                       paste0(round((beneficiarios_unicos*100)/sum(tabla_programas$beneficiarios_unicos,na.rm = TRUE),digits = 2), " %"),"0 %")) %>%
  arrange(cdprograma) %>% select(cddependencia, cdprograma,
                                           nbprograma, cdpadron,
                                           beneficiarios_unicos,
                                           porcentaje_de_beneficiarios,
                                           monto,
                                           porcentaje_de_monto)


colnames(tabla_programas) <- c("Clave de Dependencia","Clave de Programa", "Nombre de Programa", "Clave de Padrón",
                               "Beneficiarios únicos", "Porcentaje Beneficiarios", 
                               "Monto Total", "Porcentaje Monto") 

tabla_programas %>% dplyr::arrange(`Clave de Dependencia`, `Clave de Programa`,`Clave de Padrón` ) %>%
  kable() %>% 
  kable_styling() 

```

# Calidad de la información - general

```{r}
query <- glue::glue("SELECT count(distinct newid) as beneficiarios_unicos, sum(nuimpmonetario) as monto 
              FROM athena_pub.pub_cleaned_test 
              WHERE anio=2017 AND cddependencia='20' AND cdprograma IN ('{cves}') ;")
c(beneficiarios_sedesol_ALL,los_queries) := load_or_run(con,query,los_queries)

query <- glue::glue("SELECT count(distinct newid) as beneficiarios_unicos, sum(nuimpmonetario) as monto 
              FROM athena_pub.pub_cleaned_test 
              WHERE anio=2017 AND cddependencia='20' AND cdprograma IN ('{cves}')  
              AND try_cast(newid as integer) < 500000000;")

c(beneficiarios_sedesol_validos,los_queries) := load_or_run(con,query,los_queries)
beneficiarios_sedesol_validos <- beneficiarios_sedesol_validos %>%
  summarise(beneficiarios_unicos = sum(beneficiarios_unicos,na.rm = TRUE),
            monto = sum(monto,na.rm = TRUE))

query <- glue::glue("SELECT count(distinct newid) as beneficiarios_unicos, 
              sum(nuimpmonetario) as monto  
              FROM athena_pub.pub_cleaned_test 
              WHERE anio=2017 AND cddependencia='20' AND cdprograma IN ('{cves}')  
              AND try_cast(newid as integer) >= 500000000;")

c(beneficiarios_sedesol_invalidos,los_queries) := load_or_run(con,query,los_queries)

a <- bind_rows(beneficiarios_sedesol_validos, beneficiarios_sedesol_invalidos) %>% t()
colnames(a) <- c("Curp Válida (Buena Calidad)", "Curp Inválida (Calidad Insuficiente)")
a <- a %>% as_tibble(rownames=NA) #%>% mutate(percentage = validos/(validos+ invalidos)) 
rownames(a) <- c("Beneficiarios", "Montos")
a <- a %>% add_rownames(var = "tipo")

DF1 <- melt(as.data.frame(a), id.var="tipo")

a<-DF1 %>% filter(tipo=="Beneficiarios") %>% select(value) %>% sum()
b<-DF1 %>% filter(tipo=="Montos") %>% select(value) %>% sum()

p1 <- ggplot(DF1 %>% filter(tipo=="Beneficiarios"), aes(x = tipo, y = value, fill = variable)) + 
  geom_bar(stat = "identity") + xlab("") +
  theme(text = element_text(size=11)) + 
  scale_y_continuous(label=comma) + 
  ylab("Número de Beneficiarios") + 
   labs(fill = "Calidad de Identificador") + 
  geom_text(aes(label = paste0(round(value*100/a,2),"%")), 
            position = position_stack(vjust = 0.5), size = 6) 

p2 <- ggplot(DF1 %>% filter(tipo=="Montos"), aes(x = tipo, y = value, fill = variable)) + 
  geom_bar(stat = "identity") + xlab("") + ylab("Montos Otorgados") +
  theme(text = element_text(size=11)) + 
  scale_y_continuous(label=comma) + 
  labs(fill = "Calidad de Identificador") + 
  geom_text(aes(label = paste0(round(value*100/b,2),"%")), 
            position = position_stack(vjust = 0.5), size = 6) 

figure <- ggarrange(p1, p2,
                    # labels = c("A", "B"),
                    ncol = 2, nrow = 1)
figure
#ggsave(width = 100, height = 50, units = "cm", filename = "../../outputs/reporte/00_limpieza/bar_plot.png")
```

# Calidad de la información - por programa

```{r, echo=FALSE, message=FALSE, warning=FALSE}
cves <- c('S072',# prospera
          'S176',# pam 
          'S065',# paja 
          'S071',# pet 
          'S241',# SEVIJE
          'S174',# PEI
          'S052',# LICONSA
          'U009',# COMEDORES
          'U005') %>% # SEGURO POPULAR 
    paste(collapse="', '" )

query <- glue::glue("SELECT anio, cdprograma, nbprograma, sum(nuimpmonetario) as monto, count(distinct newid) as 
              beneficiarios 
              FROM athena_pub.pub_cleaned_test 
              WHERE cdprograma IN ('{cves}')
              GROUP BY anio, cdprograma, nbprograma")

c(dinero_prog_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_prog_validos) <- c("anio", "cdprograma",
                                   "nbprograma","monto_validos",
                                   "num_beneficiarios")

# Inválidos
query <- glue::glue("SELECT anio, 
              cdprograma, nbprograma, 
              sum(nuimpmonetario) as monto, 
              count(distinct newid) as beneficiarios 
           FROM athena_pub.pub_cleaned_test 
              WHERE try_cast(newid as integer) > 500000000 AND cdprograma IN ('{cves}')
              GROUP BY anio, cdprograma, nbprograma")

c(dinero_prog_invalidos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_prog_invalidos) <- c("anio","cdprograma",
                                     "nbprograma","monto_invalidos",
                                     "num_beneficiarios_invalidos")

# indicadores
names<- dinero_prog_validos %>% filter(anio == '2017') %>% select(cdprograma, nbprograma)
dinero_prog <- dinero_prog_validos %>% select(-nbprograma) %>%
  left_join(dinero_prog_invalidos%>% select(-nbprograma), by=c("anio","cdprograma")) %>%
  drop_na() %>%
  dplyr::mutate(
         proporcion_id_insuficiente = num_beneficiarios_invalidos/(num_beneficiarios_invalidos + num_beneficiarios),
         proporcion_monto_id_insuficiente = monto_invalidos/(monto_validos + monto_invalidos) ) %>%
  arrange(proporcion_id_insuficiente) %>% left_join(names)

df1 <- dinero_prog %>% select(anio, cdprograma, nbprograma,  proporcion_id_insuficiente,proporcion_monto_id_insuficiente)
df2 <- df1 %>% gather(proporcion_id_insuficiente, 
                      proporcion_monto_id_insuficiente, key = "tipo", value = "valor")
df2 <- df2 %>% filter(!cdprograma %in% c('OAX','U008', 'S048', 'S213', 'U009'))
df2 <- df2 %>% mutate(tipo = if_else(tipo=="proporcion_id_insuficiente", 
                                     "Proporción de Beneficiarios \n con id de calidad insuficiente \n\n ", "Proporción de Montos Otorgados a \n Beneficiarios con id de Calidad\n Insuficiente"))


time_s <- df2  %>% mutate(nbprograma = str_wrap(nbprograma, width = 25)) %>% 
  ggplot(aes(x = anio, y = valor, colour=tipo)) + 
  geom_line(size = 2) + 
  scale_x_continuous(breaks = seq(2011, 2017, 1))  +
  scale_y_continuous(labels=scales::percent) +
  facet_wrap(~nbprograma, nc=4) +
  theme(text = element_text(size=50)) +
  labs(color = "") + 
  theme_minimal() +
  xlab("Año") + ylab("Proporción de Montos y Beneficiarios con \n Identificación de Baja Calidad \n en programas de SEDESOL") 

time_s
# ggsave(width = 50, height = 20, units = "cm", filename = "../../outputs/reporte/00_limpieza/programa_analisis.png")

```

# Calidad de la información espacial
```{r}
# Todos
query <- glue::glue("SELECT cvemuni, sum(nuimpmonetario) as monto, 
              count(distinct newid) as beneficiarios  
              FROM athena_pub.pub_cleaned_test 
              WHERE anio=2017 AND cddependencia = '20' AND cdprograma IN ('{cves}') 
              GROUP BY cvemuni")
c(dinero_mun,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun) <- c("cve_muni","montos", "num_beneficiarios")

# Inválidos
query <- glue::glue("SELECT cvemuni, sum(nuimpmonetario) as monto, 
              count(distinct newid) as beneficiarios  
              FROM athena_pub.pub_cleaned_test  
              WHERE anio=2017 AND cast(newid as integer) > 500000000 AND cddependencia = '20'   
              AND cdprograma IN ('{cves}') 
              GROUP BY cvemuni")

c(dinero_mun_invalidos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_invalidos) <- c("cve_muni","monto_invalidos","num_beneficiarios_invalidos")

# indicadores
dinero_mun <- dinero_mun %>% left_join(dinero_mun_invalidos) %>%
  left_join(intercensal) %>%   left_join(coneval) %>% 
  drop_na() %>%
  dplyr::mutate(prop_monto_invalido = monto_invalidos/(montos + monto_invalidos),
                prop_ben_invalido = num_beneficiarios_invalidos/(num_beneficiarios_invalidos + num_beneficiarios)) %>%
  arrange(cve_muni)

municipios_nal <- geom_nal %>%
  left_join(dinero_mun)

municipios_nal$num_beneficiarios_q <- quant_labels_pct(municipios_nal$prop_ben_invalido*100)

map_ben <- ggplot(municipios_nal %>% drop_na(), aes(label=num_beneficiarios_q)) +
  geom_polygon(aes(long, lat, group=group, fill=num_beneficiarios_q))+
  labs(fill="Porcentaje de beneficiarios \ncon Id con calidad insuficiente" ) + 
  scale_fill_brewer(palette="Greens", na.value="grey") +
  #scale_fill_distiller(labels = percent) +
  coord_fixed() +
   theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size=18)) + xlab("") + ylab("") 


municipios_nal$num_beneficiarios_q <- quant_labels_pct(municipios_nal$prop_monto_invalido*100)
map_mon <- ggplot(municipios_nal %>% drop_na(), aes(label=num_beneficiarios_q)) +
  geom_polygon(aes(long, lat, group=group, fill=num_beneficiarios_q))+
  labs(fill="Porcentaje del Monto Total\n Otorgado a Beneficiarios con Id \n de calidad insuficiente" ) + 
  scale_fill_brewer(palette="Greens", na.value="grey") +
  #scale_fill_distiller(labels = percent) +
  coord_fixed() +
   theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size=18)) + xlab("") + ylab("") 

map_mon
```


# Dispersión entre municipios para mismo id único

```{r}
# Todos
# Cuántos municipios
query <- glue::glue("SELECT n_municipios, count(distinct newid) 
          FROM (SELECT newid, count(distinct cvemuni) as n_municipios 
              FROM athena_pub.pub_cleaned_test 
              WHERE anio=2017 AND cddependencia = '20' AND cdprograma IN ('{cves}') 
              GROUP BY newid) 
          GROUP BY n_municipios")
c(extendido_beneficiarios,los_queries) := load_or_run(con,query,los_queries) 
colnames(extendido_beneficiarios) <- c("Municipios", "Conteo") 

extendido_beneficiarios <- extendido_beneficiarios %>% 
  mutate(Municipios = as.factor(Municipios)) %>% arrange(Municipios)

extendido_beneficiarios  %>%  kable() %>% 
  kable_styling()

ggplot(extendido_beneficiarios, aes(Municipios, Conteo)) + 
  geom_bar(stat = "identity")

query <- glue::glue("SELECT * 
          FROM (SELECT newid, count(distinct cvemuni) as n_municipios, 
              array_agg(distinct cvemuni) as cvemuni   
              FROM athena_pub.pub_cleaned_test  
              WHERE anio=2017 AND cddependencia = '20' AND cdprograma IN ('{cves}') 
              GROUP BY newid) 
          WHERE n_municipios>1")

c(extendido_beneficiarios,los_queries) := load_or_run(con,query,los_queries)
colnames(extendido_beneficiarios) <- c("newid", "n_municipios", "cve_muni")
extendido_beneficiarios_ <- extendido_beneficiarios %>% 
  arrange(n_municipios) %>% 
  mutate(cve_muni = strsplit(str_trim(str_replace_all(cve_muni,"\\[|\\]",''),side='both'),', ')) %>%
  unnest(cve_muni)

data <- extendido_beneficiarios_ %>% group_by(cve_muni) %>% 
  summarise(n = n())  %>%
  left_join(intercensal) %>%   left_join(coneval) %>% 
  drop_na() 

map_d <- geom_nal %>%
  left_join(data)

map_d$n <- quant_labels(map_d$n)
map <- ggplot(map_d, aes(label=n)) +
  geom_polygon(aes(long, lat, group=group, fill=n))+
  labs(#title="Proporción del Monto total Otorgado a Beneficarios con identificador \n con Calidad Insuficiente por municipio", 
       fill="" )+
  scale_fill_brewer(palette="Greens", na.value="grey") +
  coord_fixed() +
   theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size=20)) + xlab("") + ylab("")


```


# Análisis de grafos
```{r}

query <- glue::glue("SELECT * 
          FROM (SELECT newid, count(distinct cveent) as n_municipios, 
              array_agg(distinct cveent) as cveent   
              FROM athena_pub.pub_cleaned_test  
              WHERE anio=2017 AND cddependencia = '20' AND cdprograma IN ('{cves}') 
              GROUP BY newid) 
          WHERE n_municipios>1")

c(extendido_beneficiarios,los_queries) := load_or_run(con,query,los_queries)
colnames(extendido_beneficiarios) <- c("newid", "n_estados", "cve_ent")
extendido_beneficiarios_ <- extendido_beneficiarios %>% 
  arrange(n_estados) %>% 
  mutate(cve_ent = strsplit(str_trim(str_replace_all(cve_ent,"\\[|\\]",''),side='both'),', ')) %>%
  unnest(cve_ent)

data <- extendido_beneficiarios_ %>% group_by(cve_ent) %>% 
  summarise(n = n())  

extendido_beneficiarios_ <- extendido_beneficiarios %>% 
  arrange(n_estados) %>% 
  mutate(cve_ent = str_replace_all(cve_ent,"\\[|\\]",'')) 


conexiones <- extendido_beneficiarios_ %>% group_by(cve_ent) %>% summarise(conexion = n()) %>% 
  arrange(-conexion) %>% separate(cve_ent, sep = ", ", into = c("from", "to")) %>% 
  group_by(from, to) %>% summarise(conexion = sum(conexion)) %>% 
  arrange(-conexion) %>% head(50)

gp_data_ <- as_tbl_graph(conexiones, directed = TRUE) 
# geom_node_point(aes(size = n), colour = 'salmon') +

gp_data_ %>%
  ggraph(layout = 'linear', circular = TRUE) +
  geom_edge_arc(aes(size = factor(conexion))) +
  geom_edge_link(alpha=.1) + 
  theme(legend.title=element_blank()) +
  geom_node_text(aes(label = name), nudge_y = 0.2, size=3) + 
  theme_graph(base_family = 'sans')

```


```{r}
intercensal <- load_table(con1,public,poblacion_intercensal_mun_2015) %>% retrieve_result()
coneval_muni <- load_table(con1,raw,coneval_municipios) %>% 
  retrieve_result() %>% filter(data_date == "2015-a") 

query <- glue::glue("SELECT cvemuni, sum(nuimpmonetario) as monto, 
              count(distinct newid) as beneficiarios 
              FROM athena_pub.pub_cleaned_test 
              WHERE anio=2017 AND newid < 500000000 AND 
              cdprograma IN ('{cves}') 
              GROUP BY cvemuni")
c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_validos) <- c("cve_muni","cuenta", "num_beneficiarios")

municipios_nal <- geom_nal %>%
  left_join(dinero_mun_invalidos)

dinero_mun_validos <- dinero_mun_validos %>%
  left_join(intercensal) %>%
  left_join(coneval_muni) %>%
  mutate(ben_entre_pob_15= num_beneficiarios/poblacion*100) %>%
  arrange(cve_muni)

municipios_nal <- geom_nal %>%
  left_join(dinero_mun_validos)

### Número de beneficiarios por municipio.
municipios_nal$num_beneficiarios_q <- quant_labels(municipios_nal$num_beneficiarios)
map <- ggplot() +
  geom_polygon(data = municipios_nal, aes(long, lat, group=group, fill=num_beneficiarios_q))+
  labs(title="Número de beneficiarios con CURP válido (ID con Buena calidad)", fill="Número de Beneficiarios")+
  scale_fill_brewer(palette="Greens", na.value="grey") +
  coord_fixed() +
  theme(axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    text = element_text(size=18)) + xlab("") + ylab("") 

municipios_nal$num_beneficiarios_q <- quant_labels_pct(municipios_nal$ben_entre_pob_15)
map_2 <- ggplot() +
  geom_polygon(data = municipios_nal, aes(long, lat, group=group, fill=num_beneficiarios_q))+
  labs(title="Porcentaje de Cobertura \n Beneficiarios con CURP válido (ID con Buena calidad) / Población total ", fill="Porcentaje de Cobertura contra\n Población Intercensal 2015")+
  scale_fill_brewer(palette="Greens", na.value="grey") +
  coord_fixed() +
  theme(axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    text = element_text(size=18)) + xlab("") + ylab("") 

map
```

```{r}

query <- glue::glue("SELECT nbprograma, cvemuni,sum(nuimpmonetario) as monto, 
              count(distinct newid) as beneficiarios 
              FROM athena_pub.pub_cleaned_test 
              WHERE anio=2017 AND cast(newid as integer) < 500000000 AND cdprograma IN ('{cves}') 
              GROUP BY cvemuni, nbprograma")

c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_validos) <- c("nbprograma","cve_muni","cuenta", "num_beneficiarios")

programas <- dinero_mun_validos %>%
  select(-cuenta) %>% 
  spread(nbprograma, num_beneficiarios) %>%
  left_join(intercensal)

scale_this <- function(x){
  (x / sum(x, na.rm=TRUE))
}

programas_ <- programas %>%
  mutate_each(funs(scale_this),-cve_muni, - poblacion) %>%
  left_join(coneval_muni) %>% 
  arrange(cve_muni)

data <- programas %>% select(-ends_with("num")) %>%
  purrr::keep(is.numeric) %>%
  drop_na()

res <-  round(cor(data), 2)
#d <- res[c(1:9),c(11:41)]
corrplot(res, type = "upper", tl.col = "black")

```


```{r}
query <- glue::glue("SELECT anio, cvemuni, sum(nuimpmonetario) as monto, count(distinct newid) as beneficiarios 
              FROM athena_pub.pub_cleaned_test 
              WHERE cast(newid as integer) < 500000000 AND cdprograma IN ('{cves}') 
              GROUP BY anio, cvemuni")
c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_validos) <- c("anio","cve_muni","cuenta", "num_beneficiarios")

conapo <- load_table(con1,raw,conapo_marginacion) %>% 
  retrieve_result() %>% filter(anio=="2015") %>% select(cve_mun, grado_marginacion) %>%
  rename(cve_muni=cve_mun)

data <- dinero_mun_validos %>% 
  left_join(conapo) %>% 
  left_join(intercensal) %>% 
  dplyr::group_by(grado_marginacion, anio, cve_muni) %>% 
  dplyr::summarise(num_beneficiarios = sum(as.numeric(num_beneficiarios), na.rm = FALSE),
            poblacion = sum(as.numeric(poblacion), na.rm = TRUE),
            cuenta = sum(as.numeric(cuenta), na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(porcentaje_cobertura = num_beneficiarios/poblacion*100,
         monto_promedio = cuenta/num_beneficiarios,
         grado_marginacion = factor(grado_marginacion,c("Muy alto","Alto","Medio","Bajo","Muy bajo"))) 

ggplot(data, aes(x=anio, y=porcentaje_cobertura, color=grado_marginacion)) +
  geom_point(position = "jitter")  +
   geom_smooth(method='loess')
  
ggplot(data, aes(x=anio, y=monto_promedio, color=grado_marginacion)) +
    geom_point(position = "jitter")  +
   geom_smooth(method='loess')


```
```{r}
query <- glue::glue("SELECT anio, count(distinct newid) as beneficiarios 
              FROM athena_pub.pub_cleaned_test 
              WHERE cast(newid as integer) < 500000000 AND 
              cdprograma IN ('{cves}') GROUP BY anio")
c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_validos) <- c("anio","n_beneficiarios")

coneval_nacional <- load_table(con1,semantic,coneval)  %>% 
  retrieve_result()%>% 
  rename(cve_ent=clave) %>%
  filter(nivel=="estatal" & tipo=="nominal") %>% 
  filter(variable %in% c("pobreza", "pobreza_e")) %>% 
  select(-data_date, -actualizacion_sedesol, -nivel, -id) %>%
  group_by(anio, variable) %>% 
  summarise(valor = sum(valor, na.rm = TRUE),
            pob_tot = sum(pob_tot, na.rm = TRUE))  %>%
  spread(key=variable, value=valor) 

data <- dinero_mun_validos %>% arrange(anio) %>% 
  left_join(coneval_nacional) %>% gather(n_beneficiarios, pobreza,
                                         pobreza_e, key=tipo, value =valor) %>%
  mutate(tipo=if_else(tipo=="n_beneficiarios", " \n Número de Beneficiarios \n (SEDESOL) \n",
                      if_else(tipo=="pobreza"," \n Personas en Situación \n de Pobreza \n",
                            if_else(tipo=="pobreza_e"," \n Personas en Situación\n de Pobreza Extrema \n",tipo)))) 

ggplot(data, aes(x=anio,y=valor,color=tipo)) +
  geom_point() + 
  geom_smooth() +
  scale_y_continuous(label=comma) + 
  xlab("Año") + ylab("Total de Beneficiarios Nivel Nacional") +
  labs(color="Tipo")


```


```{r}
query <- glue::glue("SELECT anio, cvemuni, cdprograma, 
              sum(nuimpmonetario) as monto, count(distinct newid) as beneficiarios 
              FROM athena_pub.pub_cleaned_test 
              WHERE cast(newid as integer) < 500000000 AND cdprograma IN ('{cves}') 
              GROUP BY anio, cdprograma, cvemuni")
c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_validos) <- c("anio","cve_muni","cdprograma",
                                  "cuenta", "num_beneficiarios")

names<- dinero_prog_validos %>% filter(anio == '2017') %>% select(cdprograma, nbprograma)
dinero_mun_validos <- dinero_mun_validos %>% left_join(names)

conapo <- load_table(con1,raw,conapo_marginacion) %>% 
  retrieve_result() %>% filter(anio=="2015") %>% select(cve_mun, grado_marginacion) %>%
  rename(cve_muni=cve_mun)

data <- dinero_mun_validos %>% 
  left_join(conapo) %>% 
  left_join(intercensal) %>% 
  dplyr::group_by(grado_marginacion, anio, nbprograma) %>% 
  dplyr::summarise(num_beneficiarios = sum(as.numeric(num_beneficiarios), na.rm = FALSE),
            poblacion = sum(as.numeric(poblacion), na.rm = TRUE),
            cuenta = sum(as.numeric(cuenta), na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(porcentaje_cobertura = num_beneficiarios/poblacion,
         monto_promedio = cuenta/num_beneficiarios,
         grado_marginacion = factor(grado_marginacion,c("Muy alto","Alto","Medio","Bajo","Muy bajo"))) 

# Número de Beneficiarios (Municipios en Marginación)
ggplot(data%>% drop_na(grado_marginacion), aes(x=anio, y=porcentaje_cobertura, color=grado_marginacion)) +
  geom_point()  +
   geom_smooth(method='loess') +  
  facet_wrap(~nbprograma, nc=5, 
             scales = "free", labeller = label_wrap_gen(width=20)) +
  scale_y_continuous(label=comma) + 
  xlab("Año") + ylab("Total de Beneficiarios por grado de Marginación") +
  labs(color="Grado de Marginación\n (CONAPO)") 

# Tasa de Cobertura (Municipios en Marginación)
ggplot(data%>% drop_na(grado_marginacion), 
       aes(x=anio, y=porcentaje_cobertura,
           color=grado_marginacion)) +
  geom_point()  +
   geom_smooth(method='loess') +  
  facet_wrap(~nbprograma, nc=5, 
             scales = "free", labeller = label_wrap_gen(width=20)) +
  scale_y_continuous(label=percent) + 
  xlab("Año") + ylab("Porcentaje de Cobertura (Beneficiarios/Población Total)*100") +
  labs(color="Grado de Marginación\n (CONAPO)") 

# ggplot(data, aes(x=anio, y=monto_promedio, color=grado_marginacion)) +
#     geom_point()  +
#    geom_smooth(method='loess') + facet_grid(. ~ nbprograma)
# 
# data %>% group_by(grado_marginacion) %>% summarise(monto = mean(monto_promedio,na.rm = TRUE))
# 
# d <- res[c(1:9),c(11:41)]
# corrplot(d, type = "upper", tl.col = "black")

```


# Promedio de ingreso por familia
```{r}
query <- glue::glue("SELECT anio, numespago, avg(monto) as promedio, max(max_monto) as monto_max,  
            max(monto) as suma_max, min(monto) as suma_min, 
            approx_percentile(monto, .55) as percentile_05, 
            approx_percentile(monto, .75) as percentile_07, 
            approx_percentile(monto, .95) as percentile_09, 
            approx_percentile(monto, 1) as percentile_10, 
            avg(count) as mean_n_pagos, max(count) as max_pagos 
          FROM (SELECT anio, numespago, most_common_id_hogar, count(*) as count,  
              sum(nuimpmonetario) as monto,
              max(nuimpmonetario) as max_monto
              FROM athena_pub.pub_cleaned_test 
              WHERE cast(newid as integer) < 500000000 AND cdpadron IN ('S072') 
              GROUP BY anio, numespago, most_common_id_hogar) 
          WHERE monto > 0 
          GROUP BY anio, numespago")
c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
dinero_mun_validos 
dinero_mun_validos %>% arrange(anio, numespago) %>% View()
```

Pobreza vs Beneficiarios a nivel estatal
```{r}
cves <- c('S072',# prospera
          'S176',# pam 
          'S065',# paja 
          'S071',# pet 
          'S241',# SEVIJE
          'S174',# PEI
          'S052',# LICONSA
          'U009',# COMEDORES
          'U005') %>% # SEGURO POPULAR 
    paste(collapse="', '" )

con1 <- prev_connect()

coneval_edo <- load_table(con1,semantic,coneval)  %>% 
  retrieve_result()%>% 
  rename(cve_ent=clave) %>%
  filter(nivel=="estatal") %>% 
  filter(variable %in% c("pobreza", "pobreza_e")) %>% 
  select(-data_date, -actualizacion_sedesol, -nivel, -id, -variable) %>%
  spread(key=nombre, value=valor) %>% 
  mutate(anio = as.character(anio),
         cve_ent = as.character(cve_ent)) %>% filter(tipo=="nominal")

query <- glue::glue("SELECT anio, noment, cveent, count(distinct newid) as beneficiarios 
              FROM athena_pub.pub_cleaned_test 
              WHERE cast(newid as integer) < 500000000 AND cdprograma IN ('{cves}') 
              GROUP BY anio, cveent, noment")
c(ent_ben,los_queries) := load_or_run(con,query,los_queries)
colnames(ent_ben) <- c("anio","nom_ent","cve_ent","num_beneficiarios")

ent_ben <- ent_ben %>% 
  mutate(anio = as.character(anio))

coneval_edo_ <- coneval_edo %>% select(cve_ent, anio, Pobreza, `Pobreza extrema`) %>%
  right_join(ent_ben, by=c("anio", "cve_ent")) %>% arrange(cve_ent,anio) %>% drop_na(nom_ent)

data_ <- coneval_edo_ %>% gather(Pobreza, `Pobreza extrema`,num_beneficiarios,
                                 key="tipo",value = "valor") %>% 
  mutate(tipo = if_else(tipo=="num_beneficiarios", "Beneficiarios Sedesol",tipo))

ggplot(data_,aes(x=anio,y=valor, color=tipo)) +
  geom_point() + 
  facet_wrap(~nom_ent, nc=5, scales = "free") +
  geom_smooth() +
  scale_y_continuous(label=comma) 
```

```{r}
query <- glue::glue("SELECT anio, cdprograma, 
              count(distinct newid) as beneficiarios, sum(nuimpmonetario) as monto 
              FROM athena_pub.pub_cleaned_test  
              WHERE cast(newid as integer) < 500000000 AND cdprograma IN ('{cves}') 
              GROUP BY anio, cdprograma ")
c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_validos) <- c("anio", "cdprograma",
                                  "num_beneficiarios", "cuenta")

dinero_mun_validos <- dinero_mun_validos %>% left_join(names)

# Número de Beneficiarios (Municipios en Marginación)
anual <- ggplot(dinero_mun_validos, aes(x=anio, y=num_beneficiarios)) +
  geom_point()  +
  geom_smooth(method='loess',se = FALSE) +  
  facet_wrap(~nbprograma, nc=5, scales = "free", labeller = label_wrap_gen(width=20)) +
  scale_y_continuous(label=comma) + scale_x_continuous(breaks=2011:2017) + 
  xlab("Año") + ylab("Total de Beneficiarios por Programa") +
  labs(color="Programa") 


# Mensual
query <- glue::glue("SELECT anio, numespago,  cdprograma, 
              count(distinct newid) as beneficiarios, 
              sum(nuimpmonetario) as monto  
              FROM athena_pub.pub_cleaned_test  
              WHERE cast(newid as integer) < 500000000 AND cdprograma IN ('{cves}') 
              GROUP BY anio, numespago, cdprograma")
c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_validos) <- c("anio", "mes","cdprograma",
                                  "num_beneficiarios", "cuenta")

library(zoo)
dinero_mun_validos <- dinero_mun_validos %>% left_join(names)
dinero_mun_validos <- dinero_mun_validos %>% mutate(mes_anio = paste(mes, anio, sep = '/'),
                                                    date = as.yearmon(paste(anio, mes , sep = '-')))

# Número de Beneficiarios (Municipios en Marginación)

dinero_mun_validos$date <- as.Date(dinero_mun_validos$date)

mensual <- ggplot(dinero_mun_validos, aes(x=date, y=num_beneficiarios)) +
  geom_point()  +
  geom_smooth(method='loess',se = FALSE) +  
  facet_wrap(~nbprograma, nc=5, scales = "free", labeller = label_wrap_gen(width=20)) +
  scale_y_continuous(label=comma) + 
  scale_x_date(breaks = "6 months") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  xlab("Año") + ylab("Total de Beneficiarios por Programa") +
  labs(color="Programa") 


```




# Promedios mensuales

```{r}
intercensal <- load_table(con1,public,poblacion_intercensal_mun_2015) %>% retrieve_result()
coneval_muni <- load_table(con1,raw,coneval_municipios) %>% 
  retrieve_result() %>%
  dplyr::select(cve_muni, pobreza_porcentaje, data_date)


query <- glue::glue("
    SELECT anio, numespago, cdprograma, cdpadron,  
           count(distinct(most_common_id_hogar)) as familias, 
           sum(monto) as monto 
    FROM 
        (SELECT anio, numespago, cdprograma, cdpadron,   
              most_common_id_hogar, sum(nuimpmonetario) as monto
              FROM athena_pub.pub_cleaned_test 
              WHERE cdprograma IN ('S072') 
              GROUP BY anio, numespago, cdprograma, 
                    cdpadron, most_common_id_hogar) 
    WHERE monto>0 
    GROUP BY anio, numespago, cdprograma, cdpadron" )

c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_validos) <- c("anio","numespago","programa", "padron",
                                  "num_familias", "cuenta")

dinero_mun_validos$anio <- as.factor(dinero_mun_validos$anio)
dinero_mun_validos$cuenta <- as.numeric(dinero_mun_validos$cuenta)
dinero_mun_validos$num_familias <- as.numeric(dinero_mun_validos$num_familias)

dinero_mun_validos_ <- dinero_mun_validos %>% 
  mutate(ratio = cuenta/num_familias) 

ggplot(dinero_mun_validos_, aes(x=numespago, y=ratio, color=anio)) +
  geom_point()  +
  geom_smooth() +
    facet_wrap(~anio, nc=5, 
             scales = "fix", labeller = label_wrap_gen(width=20)) +
  scale_x_continuous(breaks = seq(0, 12, 1))  +
  scale_y_continuous(breaks = seq(0, 10000, 500))  +
xlab("Decil de Pobreza Municipal") + ylab("Monto Promedio Anual por Familia") + 
  ggtitle("Promedio Monetario por Decil de Pobreza del Municipio")

```


# Promedios anuales por decil de ingreso municipal
```{r}
intercensal <- load_table(con1,public,poblacion_intercensal_mun_2015) %>% retrieve_result()
coneval_muni <- load_table(con1,raw,coneval_municipios) %>% 
  retrieve_result() %>%
  dplyr::select(cve_muni, pobreza_porcentaje, data_date)
coneval_ <- dplyr::filter(coneval_muni, data_date=="2015-a") %>% 
  mutate(decile = (ntile(pobreza_porcentaje, 10) - 11) *-1)


query <- glue::glue("
    SELECT cvemuni, anio, cdprograma, cdpadron,  
           count(distinct(most_common_id_hogar)) as familias, 
           sum(monto) as monto 
    FROM 
        (SELECT cvemuni, anio, cdprograma, cdpadron,   
              most_common_id_hogar, sum(nuimpmonetario) as monto
              FROM athena_pub.pub_cleaned_test 
              WHERE cdprograma IN ('S072') 
              GROUP BY cvemuni, anio, cdprograma, 
                    cdpadron, most_common_id_hogar) 
    WHERE monto>0 
    GROUP BY cvemuni, anio, cdprograma, cdpadron" )

c(dinero_mun_validos,los_queries) := load_or_run(con,query,los_queries)
colnames(dinero_mun_validos) <- c("cve_muni", "anio","programa", "padron",
                                  "num_familias", "cuenta")

dinero_mun_validos$anio <- as.factor(dinero_mun_validos$anio)
dinero_mun_validos$cuenta <- as.numeric(dinero_mun_validos$cuenta)
dinero_mun_validos$num_familias <- as.numeric(dinero_mun_validos$num_familias)

dinero_mun_validos_ <- dinero_mun_validos %>%
  left_join(coneval_) %>% 
  group_by(anio, decile) %>% 
  summarise(cuenta = sum(cuenta,na.rm = TRUE ),
            num_familias = sum(num_familias, na.rm = TRUE),
            ratio = cuenta/num_familias)
ggplot(dinero_mun_validos_, aes(x=decile, y=ratio, color=anio)) +
  geom_point()  +
  geom_smooth(method='loess') +
    facet_wrap(~anio, nc=5, 
             scales = "fix", labeller = label_wrap_gen(width=20)) +
  scale_x_continuous(breaks = seq(0, 12, 1))  +
xlab("Decil de Pobreza Municipal") + ylab("Monto Promedio Anual por Familia") + 
  ggtitle("Promedio Monetario por Decil de Pobreza del Municipio")

```
