---
title: "Limpieza de datos"
output: html_notebook
---

```{r}
dotenv::load_dot_env("../.env")
library(dbrsocial)
```

```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(scales)
library(maptools)
library(rgdal)
library(ggmap)
library(gridExtra)
library(Hmisc)
```

### DB conections
```{r, echo=FALSE}
con <- pub_connect(s3dir = Sys.getenv("S3_DIR"), schema = Sys.getenv("SCHEMA"))
```

### Catálogo de queries
```{r, echo=FALSE}
los_queries <- query_dic()
```

```{r, echo=FALSE}
los_estados <- read_csv("../estados.csv")
colnames(los_estados) <- c("num","id")
```

```{r}
query <- "SELECT *
          FROM athena_pub.pub_nominal
          limit 5"
c(todo,los_queries) := load_or_run(con,query,los_queries)
colnames(todo)
```

```{r}
query <- "SELECT count(*)
          FROM athena_pub.pub_nominal"
c(num_todos,los_queries) := load_or_run(con,query,los_queries)
```


```{r}
query <- "SELECT count(*)
          FROM athena_pub.pub_nominal
          WHERE newid is null"
c(nulos_newid,los_queries) := load_or_run(con,query,los_queries)
```


```{r}
query <- "SELECT count(*)
          FROM athena_pub.pub_nominal
          WHERE newid is null AND nbnombre is null
          AND nbprimerap is null AND nbsegundoap is null"
c(sin_identificar,los_queries) := load_or_run(con,query,los_queries)
sin_identificar
```


```{r}
query <- "SELECT cvemuni, cdprograma, count(*) as cuenta
          FROM athena_pub.pub_nominal
          WHERE newid is null AND nbnombre is null
          AND nbprimerap is null AND nbsegundoap is null
          GROUP BY cvemuni, cdprograma
          ORDER BY cvemuni DESC"
c(muni_noiden,los_queries) := load_or_run(con,query,los_queries)
muni_noiden[order(-muni_noiden$cuenta),]
```

```{r}
query <- "SELECT cveent, count(*) as cuenta
          FROM athena_pub.pub_nominal
          WHERE newid is null AND nbnombre is null
          AND nbprimerap is null AND nbsegundoap is null
          GROUP BY cveent
          ORDER BY cuenta DESC"
c(estado_noiden,los_queries) := load_or_run(con,query,los_queries)
colnames(estado_noiden) <- c("id","cuenta")
estado_noiden
```



```{r}
edo_shp <- readOGR("../shps/estados_ligero" , "estados_ligero")
edo_df <- fortify(edo_shp, region = "NOM_ENT")
edo_df$id %>% unique()

edos <- edo_df %>%
  left_join(los_estados) %>%
  left_join(estado_noiden)

ggplot(data = edos, aes(long, lat, group=group,fill=)) + 
  geom_polygon(colour='darkgrey', fill='white') +
  coord_map(projection="mercator") +
  theme_nothing()
```




```{r}
query <- "SELECT cdprograma, count(*) as cuenta
          FROM athena_pub.pub_nominal
          WHERE newid is null AND nbnombre is null
          AND nbprimerap is null AND nbsegundoap is null
          GROUP BY cdprograma
          ORDER BY cuenta DESC"
c(programa_noiden,los_queries) := load_or_run(con,query,los_queries)
programa_noiden
```


```{r}
query <- "SELECT DISTINCT programatipo
          FROM athena_pub.pub_nominal
          "
c(tipoprograma,los_queries) := load_or_run(con,query,los_queries)
tipoprograma
```



```{r}
query <- "SELECT count(*) as cuenta,  count(distinct newid) as distintos
          FROM athena_pub.pub_nominal
          WHERE cveent='13'"
c(totales,los_queries) := load_or_run(con,query,los_queries)
totales
```


```{r}
query <- "SELECT count(*) as cuenta,  count(distinct newid) as distintos, cveent
          FROM athena_pub.pub_nominal
          GROUP BY cveent
          ORDER BY cveent DESC"
c(totales,los_queries) := load_or_run(con,query,los_queries)
totales
```