---
title: "Análisis por persona"
output: html_notebook
---

```{r, include=FALSE, echo=FALSE}
source("../utils.R")
dotenv::load_dot_env("../.env")
library(dbrsocial)
```


### DB conections
```{r, echo=FALSE}
con <- pub_connect(s3dir = Sys.getenv("S3_DIR"), schema = Sys.getenv("SCHEMA"))
```

### Catálogo de queries
```{r, echo=FALSE}
los_queries <- query_dic()
```

```{r, echo=FALSE}
# Catálogo de Beneficios
catalogo_beneficios <- csv_s3()
colnames(catalogo_beneficios) <- c("cd_beneficio","nb_beneficio")
```

###  Programas por persona
```{r, echo=FALSE}
query <- "SELECT  year, new_id, count(distinct cve_muni) as num_muni, count(distinct cve_programa) as numero_programas
              FROM pub_nominal.nominal
              GROUP BY year, new_id
              ORDER BY num_muni DESC LIMIT 50;"
c(programas_persona,los_queries) := load_or_run(con,query,los_queries)
```


```{r, echo=FALSE}
query <-      "SELECT  anio, newid, count(distinct cveent) as num_ent, count(distinct cdprograma) as numero_programas, sum(nuimpmonetario) as monto_anual, cdbeneficio
              FROM athena_pub.pub_nominal
              GROUP BY anio, newid, cdpadron, cdbeneficio
              ORDER BY num_ent DESC LIMIT 50;"
c(monto_persona_ent,los_queries) := load_or_run(con,query,los_queries)
monto_persona_ent
```


```{r, echo=FALSE}
query <-      "SELECT anio, newid, sum(nuimpmonetario) as monto_anual, cdbeneficio
              FROM athena_pub.pub_nominal
              WHERE cdbeneficio='37'
              GROUP BY anio, newid, cdbeneficio
              ORDER BY monto_anual DESC LIMIT 50;"
c(monto_persona_ent,los_queries) := load_or_run(con,query,los_queries)
```



```{r, echo=FALSE}
query <-      "SELECT anio, newid, count(newid) as veces, sum(nuimpmonetario) as monto_anual, cdbeneficio
              FROM athena_pub.pub_nominal
              WHERE cdbeneficio='37'
              GROUP BY anio, newid, cdbeneficio
              ORDER BY monto_anual DESC LIMIT 50;"
c(monto_persona_37,los_queries) := load_or_run(con,query,los_queries)
```



```{r, echo=FALSE}
query <-      "SELECT count(*) as conteo
              FROM athena_pub.pub_nominal
              WHERE cdbeneficio='37';"
c(conteo,los_queries) := load_or_run(con,query,los_queries)
monto_persona_37$monto_anual[1]/conteo
```