---
title: "eda_nominal"
output: html_document
---

### Utils
```{r, include=FALSE, echo=FALSE}
source("../utils.R")
dotenv::load_dot_env("../.env")

```


### DB conections
```{r, echo=FALSE}
con <- dbConnect(AWR.Athena::Athena(), region='us-west-2', s3_staging_dir=Sys.getenv("S3_DIR"),
                 schema_name=Sys.getenv("SCHEMA"))

dbListTables(con)

# Catálogo de Beneficios
catalogo_beneficios <- aws.s3::s3read_using(read.csv, object = "s3://pub-raw/diccionarios/catalogo_beneficio.csv")
```

###  Programas por persona

```{r, echo=FALSE}

programas_persona <- dbGetQuery(con, 
          "SELECT  year, new_id, count(cve_programa) as numero_programas 
              FROM pub_nominal.nominal 
              GROUP BY year, new_id 
              ORDER BY numero_programas DESC LIMIT 50;")
programas_persona
```


### Montos por persona

```{r}
montos_person <- dbGetQuery(con, 
          "SELECT  year, new_id, sum(nu_imp_monetario) as monto_anual FROM 
           pub_nominal.nominal GROUP BY year, cve_padron, cd_beneficio, new_id 
           ORDER BY monto_anual DESC LIMIT 10;")
```


#### Preguntas 
Programa - temporal
- Personas recibiendo beneficios anómalos de un mismo programa 
Espacial 
- Personas que recibieron programas en múltiples municipios durante periodos cortos - ver lejanía.
Categoría
- Personas mayores/menores de edad con programas fuera de población objetivo.
