---
title: "Montos"
author: "Ollin Demian"
date: "5/29/2018"
output: html_document
---

```{r}
dotenv::load_dot_env("../.env")
library(dbrsocial)
```

```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(scales)
library(maptools)
library(rgdal)
library(ggmap)
library(gridExtra)
library(Hmisc)
```

### DB conections
```{r, echo=FALSE}
con <- pub_connect(s3dir = Sys.getenv("S3_DIR"), schema = Sys.getenv("SCHEMA"))
```

### Catálogo de queries
```{r, echo=FALSE}
los_queries <- query_dic()
```

```{r, echo=FALSE}
los_estados <- read_csv("../estados.csv")
colnames(los_estados) <- c("num","id")
```


```{r}
query <- "SELECT *
              FROM athena_pub.pub_nominal
              LIMIT 5;"
c(examp,los_queries) := load_or_run(con,query,los_queries)
examp
```


```{r}
query <- "SELECT count(distinct newid) as iden, cdprograma, sum(nuimpmonetario) as monto, cdbeneficio
              FROM athena_pub.pub_nominal
              GROUP BY cdprograma, cdbeneficio
              ORDER BY iden DESC LIMIT 50;"
c(num_per,los_queries) := load_or_run(con,query,los_queries)
num_per
```

```{r}
con1 <- prev_connect()
cuaps_p <- load_table(con1,raw,cuaps_sedesol)
cuaps_p
```

```{r}
cuaps_p <- retrive_result(cuaps_p,-1)
cuaps_p$cve_programa
num_per$cdprograma
intersect(cuaps_p$cve_programa,num_per$cdprograma)
```




```{r}
# join_tables(programas_17,cuaps_p,cdprograma,cve_programa)
join_tables(num_per,cve_programa,cuaps_p,cdprograma)
cuaps_p %>% tbl_df() %>% filter(cve_programa %in% num_per$cdprograma) %>% collect()
```

```{r}
num_per%>% tbl_df() %>% filter(cdprograma%in% cuaps_p$cve_programa) %>% collect()
```

```{r}
query <- "SELECT *
              FROM athena_pub.pub_nominal
              WHERE cdprograma='S176'"
c(pension,los_queries) := load_or_run(con,query,los_queries)
pension
```



```{r}
query <- "SELECT newid, sum(nuimpmonetario) as dinero, cdprograma
              FROM athena_pub.pub_nominal
              WHERE cdprograma='S176'
              GROUP BY newid, cdprograma"
              
              
c(pension,los_queries) := load_or_run(con,query,los_queries)
pension
```



```{r}
query <- "SELECT count(distinct newid) as iden, cdprograma, sum(nuimpmonetario) as monto, cdbeneficio
              FROM athena_pub.pub_nominal
              GROUP BY cdprograma, cdbeneficio
              ORDER BY monto LIMIT 50;"
c(menos_dinero,los_queries) := load_or_run(con,query,los_queries)
menos_dinero
```


Los que menos pagan en total
```{r}
query <- "SELECT count(distinct newid) as iden, cdprograma, sum(nuimpmonetario) as monto, cdbeneficio
              FROM athena_pub.pub_nominal
              GROUP BY cdprograma, cdbeneficio
              ORDER BY monto LIMIT 40;"
c(num_per,los_queries) := load_or_run(con,query,los_queries)
num_per
```



```{r}
query <- "SELECT newid, cdprograma, sum(nuimpmonetario) as monto, cdbeneficio
              FROM athena_pub.pub_nominal
              WHERE cdprograma='S072' AND cdbeneficio='38'
              GROUP BY newid, cdprograma, cdbeneficio
              ORDER BY monto LIMIT 40;"
c(ben38,los_queries) := load_or_run(con,query,los_queries)
ben38
```

```{r}
query <- "SELECT distinct newid as distintos, cdprograma, sum(nuimpmonetario) as monto, cdbeneficio
              FROM athena_pub.pub_nominal
              WHERE cdprograma='S072' AND cdbeneficio='38'
              GROUP BY newid, cdprograma, cdbeneficio"
c(ben38_completo,los_queries) := load_or_run(con,query,los_queries)
ben38_completo[order(ben38_completo$monto),] %>%
  subset(monto<0)
```

```{r}
ben38_completo[order(-ben38_completo$monto),] %>%
  subset(monto > 0)
```

```{r}
query <- "SELECT newid, cdprograma, sum(nuimpmonetario) as monto, cdbeneficio
              FROM athena_pub.pub_nominal
              WHERE cdprograma='13027' AND cdbeneficio='253'
              GROUP BY newid, cdprograma, cdbeneficio
              ORDER BY monto LIMIT 40;"
c(ben253,los_queries) := load_or_run(con,query,los_queries)
ben253
```



