---
title: "Análisis por persona"
output: html_notebook
---

```{r, include=FALSE, echo=FALSE}
source("../utils.R")
dotenv::load_dot_env("../.env")
library(dbrsocial)
```


### DB conections
```{r, echo=FALSE}
con <- pub_connect(s3dir = Sys.getenv("S3_DIR"), schema = Sys.getenv("SCHEMA"))
```

### Catálogo de queries
```{r, echo=FALSE}
los_queries <- query_dic()
```
```{r}
query <- "
  SELECT anio, numespago, nombreprograma, cdprograma, nombresubp1, cdpadron, 
        nombretipobeneficio, tipobeneficiario, count(distinct newid) as beneficiarios_unicos, 
        sum(monto) as monto_mensual, AVG(suma_mensual) as promedio_mensual_beneficiario,  
        AVG(numero_importes_por_benef) as numero_importes_promedio_por_benef
    FROM
    (SELECT newid, anio, numespago, nombreprograma, cdprograma, nombresubp1, cdpadron, 
        nombretipobeneficio, tipobeneficiario, 
        sum(nuimpmonetario) as monto, sum(nuimpmonetario) as suma_mensual,  
        count(nuimpmonetario) as numero_importes_por_benef  
              FROM athena_pub.pub_cleaned_test  
              WHERE cddependencia='20' AND newid < 500000000 AND anio ='2017'   
              GROUP BY newid, numespago, anio, nombreprograma, cdprograma, nombresubp1, cdpadron, tipobeneficiario,
                  nombretipobeneficio)
    WHERE monto>0 
    GROUP BY numespago, anio, nombreprograma, cdprograma, nombresubp1, cdpadron, tipobeneficiario,
                  nombretipobeneficio"

c(programas_sedesol,los_queries) := load_or_run(con,query,los_queries)

format(1e6, big.mark=",", scientific=FALSE)
programas_sedesol %>% filter(anio==2017 ) %>% arrange(anio, cdprograma, nombreprograma, nombresubp1, cdpadron, nombretipobeneficio, numespago) %>%  kable( format.args = list(decimal.mark = '.', big.mark = ",")) %>%
  kable_styling()
```

```{r}
programas_sedesol %>% filter(anio==2017 ) %>% arrange(anio, cdprograma, nombreprograma, nombresubp1, cdpadron, nombretipobeneficio, numespago) %>%  kable() %>%
  kable_styling()
```

```{r, echo=FALSE}
# Catálogo de Beneficios
catalogo_beneficios <- csv_s3()
colnames(catalogo_beneficios) <- c("cd_beneficio","nb_beneficio")
```

###  Programas por persona
```{r, echo=FALSE}
query <- "select num_muni, count(*) as conteo from (SELECT  anio, newid, count(distinct cvemuni) as num_muni, count(distinct cdprograma) as numero_programas
              FROM athena_pub.pub_nominal
              WHERE cveent='29'
              GROUP BY anio, newid) group by num_muni order by conteo desc;"
c(programas_persona,los_queries) := load_or_run(con,query,los_queries)
```

```{r}
qplot(programas_persona$num_muni)+ scale_x_log10()
table(programas_persona$num_muni)
```

```{r, echo=FALSE}
query <-      "SELECT  anio, newid, count(distinct cveent) as num_ent, count(distinct cdprograma) as numero_programas, sum(nuimpmonetario) as monto_anual, cdbeneficio
              FROM athena_pub.pub_nominal
              GROUP BY anio, newid, cdpadron, cdbeneficio
              ORDER BY num_ent DESC LIMIT 50;"
c(monto_persona_ent,los_queries) := load_or_run(con,query,los_queries)
monto_persona_ent
```


```{r, echo=FALSE}
query <-      "SELECT anio, newid, sum(nuimpmonetario) as monto_anual, cdbeneficio
              FROM athena_pub.pub_nominal
              WHERE cdbeneficio='37'
              GROUP BY anio, newid, cdbeneficio
              ORDER BY monto_anual DESC LIMIT 50;"
c(monto_persona_ent,los_queries) := load_or_run(con,query,los_queries)
monto_persona_ent
```



```{r, echo=FALSE}
query <-      "SELECT anio, newid, count(newid) as veces, sum(nuimpmonetario) as monto_anual, cdbeneficio
              FROM athena_pub.pub_nominal
              WHERE cdbeneficio='37'
              GROUP BY anio, newid, cdbeneficio
              ORDER BY monto_anual DESC LIMIT 50;"
c(monto_persona_37,los_queries) := load_or_run(con,query,los_queries)
monto_persona_37
```



```{r, echo=FALSE}
query <-      "SELECT count(*) as conteo
              FROM athena_pub.pub_nominal
              WHERE cdbeneficio='37';"
c(conteo,los_queries) := load_or_run(con,query,los_queries)
monto_persona_37$monto_anual[1]/conteo
```





```{r}
library(sp)
library(RColorBrewer)
```

```{r}
query <-      "SELECT * FROM athena_pub.pub_nominal limit 10;"
c(muestra,los_queries) := load_or_run(con,query,los_queries)
colnames(muestra)
```

```{r}
query <- "SELECT anio, cdprograma, nbprograma
          FROM athena_pub.pub_nominal
          WHERE anio=2017
          GROUP BY anio, nbprograma, cdprograma;"
c(programas_17,los_queries) := load_or_run(con,query,los_queries)
```

```{r}
con1 <- prev_connect()
cuaps_p <- load_table(con1,raw,cuaps_sedesol)
cuaps_p
```

```{r}
cuaps_p <- retrive_result(cuaps_p,158)
cuaps_p$cve_programa
programas_17$cdprograma
intersect(cuaps_p$cve_programa,programas_17$cdprograma)
```




```{r}
# join_tables(programas_17,cuaps_p,cdprograma,cve_programa)
join_tables(programas_17,cve_programa,cuaps_p,cdprograma)
cuaps_p %>% tbl_df() %>% filter(cve_programa %in% programas_17$cdprograma) %>% collect()
```

```{r}
programas_17 %>% tbl_df() %>% filter(cdprograma%in% cuaps_p$cve_programa) %>% collect()
```

